title: Foro React
icon: i-simple-icons-react

- title: 1. Introducción
  to: /es/react/1.introduccion/descripcion-del-proyecto
- title: 2. Configuración del proyecto
  to: /es/react/2.configuracion-del-proyecto/guia-inicial
- title: 3. Fundamentos de React
  to: /es/react/3.fundamentos-de-react/vision-general
- title: 4. Hooks en práctica
  to: /es/react/4.hooks-en-practica/bases-de-datos
- title: 5. Enrutamiento y layout
  to: /es/react/5.enrutamiento-y-layout/estructura-de-rutas
- title: 6. Formularios y validación
  to: /es/react/6.formularios-y-validacion/resumen
- title: 7. Datos y CRUD
  to: /es/react/7.datos-y-crud/clientes-rest
- title: 8. UI y estilos
  to: /es/react/8.ui-y-estilos/sistema-de-diseno
- title: 9. Pruebas y calidad
  to: /es/react/9.pruebas-y-calidad/estrategia
- title: 10. Despliegue y próximos pasos
  to: /es/react/10.despliegue-y-proximos-pasos/build-produccion
